# Generated by Django 6.0.3 on 2026-03-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildjob',
            name='run_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
